### ISSUE TITLE
无意间看到的，484前端同僚啊？

### ISSUE THREAD

**Issue by shaonq** [daisyHawen/daisyHawen.github.io#1]

**Comment by daisyHawen** [comment]
是的啊，这个个人网站还没有做好，正在弄

**Comment by shaonq** [comment]
推荐你看几个网址：
文档：http://www.bootcss.com/
CDN：http://www.bootcdn.cn/
TPL:http://laytpl.layui.com/ 
个人感觉jekyll太烦，我都是用json加tpl来实现数据绑定的，维护json就可以更新了

**Comment by daisyHawen** [comment]
谢谢，不过最近已经弄明白jekyll，接下来就是要好好写页面了

**Comment by shaonq** [comment]
https://www.yanyujiangnan.com.cn/ 这个是我的主页，不过是托管在国内
